config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    authenticated :user do
      root :to => 'topics#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'users/registrations#new', as: :unauthenticated_root
    end
  end

  resources :topics do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end


  resources :users, only: [:index, :show]

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]

  def create
    @comment = current_user.comments.build(comment_params)
    @topic = @comment.topic
    respond_to do |format|
      if @comment.save
        format.html { redirect_to topic_path(@topic), notice: 'コメントを投稿しました。' }
        format.js { render :index }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to topic_path(@topic), notice: "コメントを編集しました。" }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    respond_to do |format|
    @comment.destroy
    format.js { render :index }
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:topic_id, :content)
    end

    def set_comment
      @topic = Topic.find(params[:topic_id])
      @comment = @topic.comments.find(params[:id])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([topic,comment], remote: true) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= comment.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :topic_id %>
  <div class="field">
    <%= f.text_field :content, placeholder: "内容", class: "form-control"  %>
  </div>
  <div class="actions">
    <%= f.submit "コメントする", class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
      <li>
        <p class="left">
          <%= link_to user_path(comment.user) do %>
            <%= comment.user.name %>
          <% end %>
            さんがコメントしました。</p>
        <p class="left"><%= comment.content %></p>
        <% if current_user.id == comment.user.id %>
          <p class="right">
            <%= link_to '', edit_topic_comment_path(topic, comment), class: "fa fa-pencil-square-o fa-lg" %>
            <%= link_to '', topic_comment_path(topic, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
          </p>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/edit.html.erb
<div class="col-xs-12 col-sm-6 col-sm-offset-3">

  <div class="row" style="background-color:#fafafa; border-radius: 0.3em; padding: 10px 10px 10px 10px; margin-bottom: 20px;">

    <h2 style="text-align:center; border-bottom:#DCDCDC 1px solid;">
      コメントの編集
    </h2>

    <%= form_for(@comment, url: topic_comment_path) do |f| %>

    <%= f.label :内容 %>
    <%= f.text_field :content, class: 'form-control' %>
    <br>
    <%= f.submit '編集する', class: 'btn btn-primary btn-block' %>
    <% end %>

    <div style="text-align:center;">
    <%= link_to "詳細画面にもどる", topic_path(@topic) %>
    </div>

  </div>
</div>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.topic.comments, topic: @comment.topic }) %>")
$(':text').val('')