config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    authenticated :user do
      root :to => 'topics#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'users/registrations#new', as: :unauthenticated_root
    end
  end

  resources :topics do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end


  resources :users, only: [:index, :show]

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :caption, presence: true

  belongs_to :user
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  def like_user(user_id)
   likes.find_by(user_id: user_id)
  end

  default_scope -> { order(created_at: :desc) }

  mount_uploader :file, PictureUploader
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def index
    @topics = Topic.all.page(params[:page]).per(20)
    @likes = Like.where(topic_id: params[:topic_id])
  end

  def show
    @comment = @topic.comments.build
    @comments = @topic.comments
    @likes = Like.where(topic_id: params[:topic_id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id
    if @topic.save
      redirect_to topics_path, notice: "投稿しました！"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @topic.update(topic_params)
      redirect_to topics_path, notice: "投稿を編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @topic.destroy
    redirect_to topics_path, notice: "投稿を削除しました！"
  end


  private
  def topic_params
    params.require(:topic).permit(:caption, :file)
  end

  def set_topic
    @topic = Topic.find(params[:id])
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
  def choose_new_or_edit
    if action_name == 'new'
      topics_path
    elsif action_name == 'edit'
      topic_path
    end
  end
end

app/views/topics/_each_do.erb
<div class="jscroll-added">

  <% @topics.each do |topic| %>

    <div class="row" style="background-color:#fafafa; border-radius: 0.3em; padding: 10px 10px 10px 10px; margin-bottom: 20px;">

      <div class="boxContainer" style="padding-bottom: 10px;">
      	<div class="box" style="margin-right: 10px;">
          <%= link_to user_path(topic.user) do %>
            <%= profile_img_topics(topic.user) if profile_img_topics(topic.user) %>
        </div>

      	<div class="box">
          <div>
            <%= topic.user.name %>
            <% end %>
          </div>
      	  <div>
            <%= topic.updated_at.strftime("%m/%d(#{%w(日 月 火 水 木 金 土)[topic.updated_at.wday]}) %k:%M") %>
          </div>
        </div>

        <div class="box" style="position: absolute; right: 0;">
          <% if current_user.id === topic.user_id %>
            <div style="text-align: right;">
              <ul class="nav">
                <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" style="width: 60px; padding: 5px 0 5px 0;">
                    <img src="<%= asset_path "chevron-down.png" %>" style="width: 60px;" >
                  </a>
                  <ul class="dropdown-menu left">
                    <li><a href="#">投稿を保存</a></li>
                    <li class="divider"></li>
                    <li><%= link_to "投稿を編集", edit_topic_path(topic.id) %></li>
                    <li><a href="#">日付を変更</a></li>
                    <li><a href="#">埋め込み</a></li>
                    <li><a href="#">この投稿に関するお知らせをオフにする</a></li>
                    <li><a href="#">タブで表示</a></li>
                    <li class="divider"></li>
                    <li><a href="#">タイムラインに表示しない</a></li>
                    <li><%= link_to "削除する", topic_path(topic.id), method: :delete, data: { confirm: '本当に削除していいですか？'} %></li>
                    <li><a href="#">翻訳をオフにする</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          <% end %>
        </div>
      </div>

      <div style="font-size: 14px; padding-bottom: 10px;">
        <%= topic.caption %>
      </div>

      <% if topic.file? %>
        <div style="padding-bottom: 15px;">
          <%= image_tag(topic.file_url, :width => "auto") %>
        </div>
      <% end %>


      <div class="boxContainer" style="border-top:#DCDCDC 1px solid;">
      	<div class="box" style="margin: 10px 10px 10px 0;">
          <%= render partial: 'likes/like', locals: { topic: topic, likes: @likes } %>
        </div>
        <div class="box" style="margin: 10px 10px 10px 0; line-height: 25px;">
          <%= link_to topic_path(topic) do %>
            コメントする
          <% end %>
        </div>
      </div>


      <% if topic.comments.last %>
        <%= link_to topic_path(topic) do %>
        <span style="color: black;">
          ・<%= topic.comments.last.user.name %>さんがコメントしました。「<%= topic.comments.last.content %>」
        </span>
        <% end %>
      <% end %>

    </div>

  <% end %>

  <%= link_to_next_page @topics, 'もっと見る', id: 'more_link' %>

</div>

app/views/topics/_form.html.erb
<%= form_for(@topic, url: choose_new_or_edit) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= @topic.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @topic.file? %>
    <%= image_tag(@topic.file_url, :width => "auto") %>
  <% end %>
  <br>
  <%= f.label :キャプション %>
  <%= f.text_field :caption, class: 'form-control' %>
  <br>
  <%= f.label :写真 %>
  <%= f.file_field :file, class: 'form-control' %>
  <%= f.hidden_field :file_cache %>
  <div class="preview"></div>
  <br>
  <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>
<div style="text-align:center;">
  <%= link_to "一覧画面にもどる", topics_path %>
</div>

app/views/topics/edit.html.erb
<div class="col-xs-12 col-sm-6 col-sm-offset-3">

  <div class="row" style="background-color:#fafafa; border-radius: 0.3em; padding: 10px 10px 10px 10px; margin-bottom: 20px;">

    <h2 style="text-align:center; border-bottom:#DCDCDC 1px solid;">
      投稿の編集
    </h2>

    <%= render 'form' %>

  </div>
</div>

app/views/topics/index.html.erb
<div class="row">
  <div class="hidden-xs col-sm-3">

    <ul class="sidebar nav nav-stacked affix">
      <li>
        <%= link_to user_path(current_user) do %>
        <%= profile_img_header(current_user) if profile_img_header(current_user) %>
        <%= current_user.name %>
        <% end %>
      </li>
      <li><a>ニュースフィード</a></li>
      <li><a>Messenger</a></li>
      <li><a>ショートカット</a></li>
      <li><a>イベント</a></li>
      <li><a>Facebookページ</a></li>
      <li><a>グループ</a></li>
      <li><a>Poke</a></li>
      <li><%= link_to '友達を検索', users_path %></li>
      <li><a>保存済み</a></li>
      <li><a>友達リスト</a></li>
      <li><a>インサイト</a></li>
      <li><a>ゲーム</a></li>
      <li><a>ライブ動画</a></li>
      <li><a>▼ もっと見る</a></li>

    </ul>
  </div>

  <div class="col-xs-12 col-sm-7 col-md-6 testjsc">
    <div class="row" style="margin-bottom: 10px;">
      <%= link_to new_topic_path, class: 'btn btn-default btn-block whatnow' do %>
        <%= profile_img_header(current_user) if profile_img_header(current_user) %>
        <span style="margin-left: 5px;">今なにしてる？</span>
      <% end %>
    </div>
    <%= render partial: 'each_do', locals: { topics: @topics, likes: @likes } %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="col-xs-12 col-sm-6 col-sm-offset-3">

  <div class="row" style="background-color:#fafafa; border-radius: 0.3em; padding: 10px 10px 10px 10px; margin-bottom: 20px;">

    <h2 style="text-align:center; border-bottom:#DCDCDC 1px solid;">
      トピックの投稿
    </h2>

    <%= render 'form' %>

  </div>
</div>

app/views/topics/show.html.erb
<div class="col-xs-12 col-sm-6 col-sm-offset-3">

  <div class="row" style="background-color:#fafafa; border-radius: 0.3em; padding: 10px 10px 10px 10px; margin-bottom: 20px;">


    <div class="boxContainer" style="padding-bottom: 10px;">
    	<div class="box" style="margin-right: 10px;">
        <%= link_to user_path(@topic.user) do %>
          <%= profile_img_topics(@topic.user) if profile_img_topics(@topic.user) %>
      </div>

    	<div class="box">
        <div>
          <%= @topic.user.name %>
          <% end %>
        </div>
    	  <div>
          <%= @topic.updated_at.strftime("%m/%d(#{%w(日 月 火 水 木 金 土)[@topic.updated_at.wday]}) %k:%M") %>
        </div>
      </div>

      <div class="box" style="position: absolute; right: 0;">
        <% if current_user.id === @topic.user_id %>
          <div style="text-align: right;">
            <ul class="nav">
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" style="width: 60px; padding: 5px 0 5px 0;">
                  <img src="<%= asset_path "chevron-down.png" %>" style="width: 60px;" >
                </a>
                <ul class="dropdown-menu left">
                  <li><a href="#">投稿を保存</a></li>
                  <li class="divider"></li>
                  <li><%= link_to "投稿を編集", edit_topic_path(@topic.id) %></li>
                  <li><a href="#">日付を変更</a></li>
                  <li><a href="#">埋め込み</a></li>
                  <li><a href="#">この投稿に関するお知らせをオフにする</a></li>
                  <li><a href="#">タブで表示</a></li>
                  <li class="divider"></li>
                  <li><a href="#">タイムラインに表示しない</a></li>
                  <li><%= link_to "削除する", topic_path(@topic.id), method: :delete, data: { confirm: '本当に削除していいですか？'} %></li>
                  <li><a href="#">翻訳をオフにする</a></li>
                </ul>
              </li>
            </ul>
          </div>
        <% end %>
      </div>
    </div>

    <div style="font-size: 14px; padding-bottom: 10px;">
      <%= @topic.caption %>
    </div>

    <% if @topic.file? %>
      <div style="padding-bottom: 15px;">
        <%= image_tag(@topic.file_url, :width => "auto") %>
      </div>
    <% end %>


    <div class="boxContainer" style="border-top:#DCDCDC 1px solid;">
    	<div class="box" style="margin: 10px 10px 10px 0;">
        <%= render partial: 'likes/like', locals: { topic: @topic, likes: @likes } %>
      </div>
    </div>


    <p>コメント一覧</p>
      <div id="comments_area">
        <%= render partial: 'comments/index', locals: { comments: @comments, topic: @topic } %>
      </div>
      <%= render partial: 'comments/form', locals: { comment: @comment, topic: @topic } %>
    <div style="text-align:center;">
      <%= link_to "一覧画面にもどる", topics_path %>
    </div>
  </div>
</div>