config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    authenticated :user do
      root :to => 'topics#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'users/registrations#new', as: :unauthenticated_root
    end
  end

  resources :topics do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end


  resources :users, only: [:index, :show]

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :topics ,dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :like_topics, through: :likes, source: :topic

  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy

  has_many :followed_users, through: :relationships, source: :followed
  has_many :followers, through: :reverse_relationships, source: :follower

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, :lockable, :timeoutable

         mount_uploader :avatar, AvatarUploader

   def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
     user = User.find_by(email: auth.info.email)

     unless user
       user = User.new(
           name:     auth.extra.raw_info.name,
           provider: auth.provider,
           uid:      auth.uid,
           email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
           image_url:   auth.info.image,
           password: Devise.friendly_token[0, 20]
       )
       user.skip_confirmation!
       user.save(validate: false)
     end
     user
   end

   def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
     user = User.find_by(provider: auth.provider, uid: auth.uid)

     unless user
       user = User.new(
           name:     auth.info.nickname,
           image_url: auth.info.image,
           provider: auth.provider,
           uid:      auth.uid,
           email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
           password: Devise.friendly_token[0, 20]
       )
       user.skip_confirmation!
       user.save
     end
     user
   end

   def self.create_unique_string
     SecureRandom.uuid
   end

   def update_with_password(params, *options)
     if provider.blank?
       super
     else
       params.delete :current_password
       update_without_password(params, *options)
     end
   end


   def self.search(search)
     if search
       where(['name LIKE ?', "%#{search}%"])
     else
       all
     end
   end


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @userselect = User.search(params[:search])
    @users = @userselect.where.not(id: current_user.id).page(params[:page]).per(18)
  end

  def show
    @user = User.find(params[:id])
    @topics = @user.topics.page(params[:page]).per(10)
    @likes = Like.where(topic_id: params[:topic_id])
  end

end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user.following?(user) %>
    <%= form_for(current_user.relationships.build(followed_id: user.id), remote: true) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー", class: "btn btn-large btn-primary" %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.find_by(followed_id: user.id), html: { method: :delete }, remote: true) do |f| %>
      <%= f.submit "つながりを解除", class: "btn btn-large" %>
    <% end %>
  <% end %>
</div>

app/views/users/_followed_users.html.erb
・フォローユーザー 一覧
<br>
<% @user.followed_users.each do |user| %>
  <%= link_to user_path(user) do %>
    <%= profile_img_users(user) %>
    <%= user.name %>
  <% end %>
  <br>
<% end %>

app/views/users/_followers.html.erb
・フォロワーユーザー 一覧
<br>
<% @user.followers.each do |user| %>
  <%= link_to user_path(user) do %>
    <%= profile_img_users(user) %>
    <%= user.name %>
  <% end %>
  <br>
<% end %>

app/views/users/index.html.erb
<div class="row">
  <h2>知り合いかも(ユーザー一覧)</h2>

  <% @users.each do |user| %>
      <div class="container-child col-md-2 col-sm-4 col-xs-6 " style="margin-top: 10px; border-right:#DCDCDC 1px solid;">
        <%= link_to user_path(user) do %>
          <%= profile_img_users(user) %>
          <div></div>
          <%= user.name %>
        <% end %>

        <% if user.id != current_user.id %>

          <%= render partial: 'follow_form', locals: { user: user } if signed_in?   %>

          <div class="btn btn-default">
            <%= link_to '新しいメッセージ', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post'%>
          </div>

        <% end %>
      </div>
  <% end %>
</div>

<div class="row" style="text-align: center;">
  <%= paginate @users %>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-7 col-sm-offset-3 col-md-6 col-md-offset-3">

    <div class="row">
      <%= profile_img_users(@user) %>
      <%= @user.name %>
      <br>
      <% if @user.id != current_user.id %>
        <div class="boxContainer" style="padding: 10px 0 10px 0;">
        	<div class="box" style="margin-right: 10px;">
            <%= render partial: 'follow_form', locals: { user: @user } %>
          </div>
          <div class="box btn btn-default">
            <%= link_to '新しいメッセージ', conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: 'post'%>
          </div>
        </div>
      <% end %>
    </div>

    <div class="row" role="tabpanel">

        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="active">
            <a href="#contents1" aria-controls="contents1" role="tab" data-toggle="tab">タイムライン</a>
          </li>
          <li role="presentation">
            <a href="#contents2" aria-controls="contents2" role="tab" data-toggle="tab">基本データ</a>
          </li>
          <li role="presentation">
            <a href="#contents3" aria-controls="contents3" role="tab" data-toggle="tab">友達（フォロワー）</a>
          </li>
          <li role="presentation">
            <a href="#contents4" aria-controls="contents3" role="tab" data-toggle="tab">写真</a>
          </li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="contents1">

            <% if current_user.id === @user.id %>
              <div style="margin-top: 10px; margin-bottom: 10px;">
                <%= link_to new_topic_path, class: 'btn btn-default btn-block whatnow' do %>
                  <%= profile_img_header(current_user) if profile_img_header(current_user) %>
                  <span style="margin-left: 5px;">今なにしてる？</span>
                <% end %>
              </div>
            <% end %>

            <div class="testjsc" style="padding: 0 15px 0 15px;">
              <%= render partial: 'topics/each_do', locals: { topics: @topics, likes: @likes } %>
            </div>

          </div>
          <div role="tabpanel" class="tab-pane" id="contents2">

            <p>概要</p>
            <p>職歴と学歴</p>
            <p>住んだことがある場所</p>
            <p>連絡先と基本データ</p>
            <p>家族と交際ステータス</p>
            <p>詳細情報</p>
            <p>ライフイベント</p>

          </div>
          <div role="tabpanel" class="tab-pane" id="contents3">

            <%= render partial: 'users/followed_users', locals: { user: @user } %>
            <br>
            <%= render partial: 'users/followers', locals: { user: @user } %>

          </div>
          <div role="tabpanel" class="tab-pane" id="contents4">

            <% @topics.each do |topic| %>
              <% if topic.file? %>
                <div style="padding:3px 3px 3px 3px;">
                <%= link_to topic_path(topic) do %>
                  <%= image_tag(topic.file_url, :width => "auto") %>
                <% end %>
              </div>
              <% end %>
            <% end %>

          </div>
        </div>
    </div>

  </div>
</div>